import Head from 'next/head'
import React from 'react';
import crypto from '../styles/Crypto.module.css'
import SplashScreen from './componentsAccount/JavaScriptDocs/SplashScreen'

export default function İndex() {
  return (
    <div className={crypto.all_page}>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by Bedirhan Cakir" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={crypto.container}>
        <SplashScreen />
      </div>
    </div>
  )
}
